### ISSUE TITLE
도서를 읽다가 문제(Issues)가 발생하면 이 곳에 질문주세요~ ^^

### ISSUE THREAD

**Issue by yamoo9** [yamoo9/Making-Modern-Web-Design-Work-Process#1]
이 곳은 이슈를 다루고 해결하는 공간입니다~

**Comment by yamoo9** [comment]
이슈가 발생하면 최대한 빠른 시간 내에 해결할 수 있도록 노력하겠습니다~ 감사합니다 ^^

**Comment by implict** [comment]
p.268에서 gulp를 실행시킬 경우 아래와 같은 에러가 발생합니다.

Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at ConnectApp.server (/Users/jiwonpark/Documents/jade-project-begin/node_modules/gulp-connect/index.js:57:19)
    at new ConnectApp (/Users/jiwonpark/Documents/jade-project-begin/node_modules/gulp-connect/index.js:37:10)
    at Object.module.exports.server (/Users/jiwonpark/Documents/jade-project-begin/node_modules/gulp-connect/index.js:170:12)
    at Gulp.<anonymous> (/Users/jiwonpark/Documents/jade-project-begin/gulpfile.js:30:10)
    at module.exports (/Users/jiwonpark/Documents/jade-project-begin/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jiwonpark/Documents/jade-project-begin/node_modules/gulp/node_modules/orchestrator/index.js:273:3)

**Comment by motion2015** [comment]
안녕하세요. 이번책 내용도 너무 좋아서 잘 보고 있습니다. 
질문만 간단히 쓰겠습니다. 
jade 학습을 위한 기본준비장에서요.
파일을 다운받아서 설치 모듈들을 전부설치하고 gulp default 로 명령어를 실행했는데.아래와 같은 에러메세지가 뜨면서 웹브라우저는 안열립니다. 

감사합니다. 

$ gulp default
[22:04:18] Using gulpfile D:\jade-project-begin\gulpfile.js
[22:04:18] Starting 'serve'...
[22:04:18] Finished 'serve' after 132 ms
[22:04:18] Starting 'open'...
[22:04:18] Finished 'open' after 12 ms
[22:04:18] Starting 'watch'...
[22:04:18] Finished 'watch' after 20 ms
[22:04:18] Starting 'default'...
[22:04:18] Finished 'default' after 5.13 μs
[22:04:18] Server started http://localhost:90
[22:04:18] LiveReload started on port 35729
D:\jade-project-begin\node_modules\gulp-open\index.js:22
      opts.uri = file.path;
               ^

TypeError: Cannot assign to read only property 'uri' of <%file.path%>
    at DestroyableTransform._transform (D:\jade-project-begin\node_modules\gulp-open\index.js:22:16)
    at DestroyableTransform.Transform._read (D:\jade-project-begin\node_modules\gulp-open\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (D:\jade-project-begin\node_modules\gulp-open\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:172:12)
    at doWrite (D:\jade-project-begin\node_modules\gulp-open\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:237:10)
    at writeOrBuffer (D:\jade-project-begin\node_modules\gulp-open\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (D:\jade-project-begin\node_modules\gulp-open\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:194:11)
    at write (D:\jade-project-begin\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:623:24)
    at flow (D:\jade-project-begin\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (D:\jade-project-begin\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib_stream_readable.js:664:5)
    at emitNone (events.js:67:13)

**Comment by yamoo9** [comment]
안녕하세요 @motion2015 님.  ^^ 야무입니다.
말씀주신 문제는 제가 원격으로 접속해서 확인해드렸으면 하네요.
시간되실 때 문자(010-9814-1461) 주세요. [팀뷰어](https://www.teamviewer.com/ko/index.aspx?pid=google.tv_exact.s.int&gclid=CNGon-Lhv8gCFRUJvAod29QCZg)로 접속해서 원격으로 봐드릴께요 ^^
그래야 문제를 해결해드릴 수 있을 것 같네요. 그럼 연락주세요~
